spring:
   search:
    backend:
     analysis:
      configurer: by.alex.commentAppMicriservice.configuration.LuceneConfig
     directory:
      root: src/main/resources/db.changelog/index
   cache:
    algorithm: LRU
    max_size: 1000
server:
  port: 8082
