spring:
            search:
            backend:
              analysis:
                configurer: by.alex.commentAppMicriservice.configuration.LuceneConfig
              directory:
                root: src/main/resources/db.changelog/index

server:
  port: 8082
