spring:
  jpa:
      hibernate:
        ddl-auto: none
        show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          search:
            backend:
              analysis:
                configurer: by.alex.newsappmicriservice.configuration.LuceneConfig
              directory:
                root: src/main/resources/db.changelog/index
server:
  port: 8081
